const images = {
  ic_app: require('./images/ic_app.png'),
  ic_arrow_up: require('./images/ic_arrow_up.png'),
  ic_back: require('./images/ic_back.png'),
  ic_camera: require('./images/ic_camera.png'),
  ic_check: require('./images/ic_check.png'),
  ic_close: require('./images/ic_close.png'),
  ic_copy: require('./images/ic_copy.png'),
  ic_empty: require('./images/ic_empty.png'),
  ic_empty_list_address: require('./images/ic_empty_list_address.png'),
  ic_eye_close: require('./images/ic_eye_close.png'),
  ic_feed: require('./images/ic_feed.png'),
  ic_feed_color: require('./images/ic_feed_color.png'),
  ic_invisible: require('./images/ic_invisible.png'),
  ic_list_address: require('./images/ic_list_address.png'),
  ic_lock: require('./images/ic_lock.png'),
  ic_menu: require('./images/ic_menu.png'),
  ic_nft: require('./images/ic_nft.png'),
  ic_nft_color: require('./images/ic_nft_color.png'),
  ic_polygon: require('./images/ic_polygon.png'),
  ic_profile: require('./images/ic_profile.png'),
  ic_profile_color: require('./images/ic_profile_color.png'),
  ic_qr_code: require('./images/ic_qr_code.png'),
  ic_qr_color: require('./images/ic_qr_color.png'),
  ic_search: require('./images/ic_search.png'),
  ic_select_camera: require('./images/ic_select_camera.png'),
  ic_select_photo: require('./images/ic_select_photo.png'),
  ic_visible: require('./images/ic_visible.png'),
  ic_wallet: require('./images/ic_wallet.png'),
  ic_wallet_color: require('./images/ic_wallet_color.png'),
  img_bg_frame: require('./images/img_bg_frame.png'),
  img_frame: require('./images/img_frame.png'),
  img_splash: require('./images/img_splash.png'),
};
export default images;
